sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.140.163
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: 192.168.140.163
    port: 6379
    database: 0


#图片存储路径，使用绝对路径
image:
  base-image-path: D:/dev/code/sky-take-out/sky-server/src/main/resources/images/
